### ISSUE TITLE
Need functional tests

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/nmr_preprocessing#1]
@mtremblayfr 
Si tu veux, tu peux ajouter un dossier `test-data` avec les fichiers de test et les bons paramètres, je mettrais en place les `<test>` si tu veux. 
Après, ça n'est pas bien dur, tu peux commencer et j'y jetterais un oeil si tu veux.

Par contre, il va falloir gérer les dépendences:

- [x] batch
- [x] ggplot2
- [x] gridExtra
- [x] reshape2
- [x] ptw
- [x] Matrix

Lequel correspond au package NMR non publié ? ptw ?

**Comment by ManonMartin** [comment]
@lecorguille 
J'ai ajouté des tests pour les modules NMR_Read et NMR_Preprocessing mais le test du preprocessing ne passe pas et je n'arrive pas à voir d'où vient l'erreur (branche _AllNew_). J'ai repris la nomenclature des tests dans le xml d'après les tests de @mtremblayfr 
Si tu as un indice d'où cela pourrait provenir ça m'aiderait !
